const TOGGLE_RECORDING = 'TOGGLE_RECORDING';
const ADD_TRANSCRIPTION = 'ADD_TRANSCRIPTION';

const ADD_LABEL = 'ADD_LABEL';
const REQUEST_ANALYSIS = 'REQUEST_ANALYSIS';
const RECEIVE_ANALYSIS = 'RECEIVE_ANALYSIS';
const REQUEST_ACTION = 'REQUEST_ACTION';
const RECEIVE_ACTION = 'RECEIVE_ACTION';

const REQUEST_NODE_LABEL = 'REQUEST_NODE_LABEL';
const RECEIVE_NODE_LABEL = 'RECEIVE_NODE_LABEL';
const TOGGLE_ALL_LABELS = 'TOGGLE_ALL_LABELS';

const OPEN_STANDARD_MODAL = 'OPEN_STANDARD_MODAL';
const OPEN_CALCULATION_MODAL = 'OPEN_CALCULATION_MODAL';
const OPEN_SURVEY_MODAL = 'OPEN_SURVEY_MODAL';
const OPEN_SEARCH_MODAL = 'OPEN_SEARCH_MODAL';
const OPEN_IMAGE_MODAL = 'OPEN_IMAGE_MODAL';
const OPEN_VIDEO_MODAL = 'OPEN_VIDEO_MODAL';
const OPEN_NEWS_MODAL = 'OPEN_NEWS_MODAL';
const OPEN_WEATHER_MODAL = 'OPEN_WEATHER_MODAL';
const OPEN_MAPS_MODAL = 'OPEN_MAPS_MODAL';
const GET_GEO_LOCATION = 'GET_GEO_LOCATION';
const OPEN_HELP_MODAL = 'OPEN_HELP_MODAL';

const SUBMIT_MODAL = 'SUBMIT_MODAL';

// Action types for authentication
const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNUP = 'USER_SIGNUP';
const USER_SIGNOUT = 'USER_SIGNOUT';
const REDIRECT_SIGNIN = 'REDIRECT_SIGNIN';
const REDIRECT_SIGNUP = 'REDIRECT_SIGNUP';
const GET_QUOTE = 'GET_QUOTE';

export {
  TOGGLE_RECORDING,
  ADD_TRANSCRIPTION,
  ADD_LABEL,
  REQUEST_ANALYSIS,
  RECEIVE_ANALYSIS,
  REQUEST_ACTION,
  RECEIVE_ACTION,
  REQUEST_NODE_LABEL,
  RECEIVE_NODE_LABEL,
  TOGGLE_ALL_LABELS,
  OPEN_STANDARD_MODAL,
  OPEN_CALCULATION_MODAL,
  OPEN_SURVEY_MODAL,
  OPEN_SEARCH_MODAL,
  OPEN_IMAGE_MODAL,
  OPEN_VIDEO_MODAL,
  OPEN_NEWS_MODAL,
  OPEN_WEATHER_MODAL,
  OPEN_MAPS_MODAL,
  OPEN_HELP_MODAL,
  SUBMIT_MODAL,
  USER_SIGNIN,
  USER_SIGNUP,
  USER_SIGNOUT,
  REDIRECT_SIGNIN,
  REDIRECT_SIGNUP,
  GET_QUOTE,
  GET_GEO_LOCATION,
};
