const TOGGLE_RECORDING = 'TOGGLE_RECORDING';
const ADD_TRANSCRIPTION = 'ADD_TRANSCRIPTION';
const SET_SURVEY = 'SET_SURVEY';
const ADD_LABEL = 'ADD_LABEL';
const REQUEST_ANALYSIS = 'REQUEST_ANALYSIS';
const RECEIVE_ANALYSIS = 'RECEIVE_ANALYSIS';
const REQUEST_ACTION = 'REQUEST_ACTION';
const RECEIVE_ACTION = 'RECEIVE_ACTION';
const REQUEST_NODE_LABEL = 'REQUEST_NODE_LABEL';
const RECEIVE_NODE_LABEL = 'RECEIVE_NODE_LABEL';
const TOGGLE_ALL_LABELS = 'TOGGLE_ALL_LABELS';

export {
  TOGGLE_RECORDING,
  ADD_TRANSCRIPTION,
  SET_SURVEY,
  ADD_LABEL,
  REQUEST_ANALYSIS,
  RECEIVE_ANALYSIS,
  REQUEST_ACTION,
  RECEIVE_ACTION,
  REQUEST_NODE_LABEL,
  RECEIVE_NODE_LABEL,
  TOGGLE_ALL_LABELS,
};
